import Head from 'next/head';
import Link from '../components/LinkCards';
import Header from '../components/Header';
import LanguageSwitchButtons from '../components/LanguageSwitchButtons';
import useLanguageStore from '../lib/store';
import { getTranslation } from '../lib/language';
import CountdownTimer from '../components/CountdownTimer';

export default function Home() {
  const { language } = useLanguageStore((state) => ({
    language: state.language,
  }));
  const translation = getTranslation(language);

  const locationLink =
    'https://www.google.com/maps/place/Lord+Milner+Hotel+(Matjiesfontein)/@-33.2310257,20.5799933,17z/data=!3m1!4b1!4m9!3m8!1s0x1dd3110f98e906e5:0x40d4cb7334e175dd!5m2!4m1!1i2!8m2!3d-33.2310302!4d20.582182!16s%2Fg%2F1tc_hj29';

  const isAfrikaans = language === 'afr';

  return (
    <>
      <Head>
        <title>Duminy Troue</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-[#EFDDCD] pt-5 mb-12'>
        <LanguageSwitchButtons />

        <div className='text-7xl pt-10 pb-5 text-[#102135]'>
          <h1>Theunis</h1>
          <h1>&</h1>
          <h1>Mignon</h1>
          {/* <h1 className='pt-10 text-center'>{weddingTitle} 💍</h1> */}
        </div>
        <Header link='theunis-mignon-min.png' />

        <div className='pt-5 text-center items-center bg-gradient-to-b from-[#EFDDCD] to-white'>
          {/* Date + counter */}
          <div className='pb-6'>
            <CountdownTimer targetDate={new Date('2024-03-23T15:00:00')} />
            <p className='text-4xl text-[#102135] py-5'>
              22-24 {translation.month}, 2024
            </p>
          </div>

          {/* Lord Milner picture */}
          <div className='text-center max-w-2xl mx-auto flex flex-col items-center justify-center pb-10'>
            <img
              src='./images/lord-milner-no-bg-min.png'
              className='w-[80%] md:w-70 md:px-20'
              alt='Header Image'
            />
            <div className='px-10 text-lg'>
              <p>
                {translation.waar_die_troue_is_1}{' '}
                <a href={locationLink} className='text-3xl'>
                  <strong className='text-[#4077a9] py-5 hover:underline'>
                    Matjiesfontein
                  </strong>
                </a>
              </p>
              <p className='pt-1'>{translation.waar_die_troue_is_2}</p>
            </div>
          </div>

          {/* Cards for linking to other pages */}
          <Link showBackToHome={false} language={language} />
        </div>
      </main>
      {/* Footer element */}
      <footer className='border-solid border-t-2 border-[#102135]'>
        <span>Gebou deur Theunis.</span>
      </footer>
    </>
  );
}
