import Head from 'next/head';
import Link from '../components/LinkCards';
import Header from '../components/Header';
import LanguageSwitchButtons from '../components/LanguageSwitchButtons';
import useLanguageStore from '../lib/store';
import { getTranslation } from '../lib/language';

export default function Home() {
  const { language } = useLanguageStore((state) => ({
    language: state.language,
  }));
  const translation = getTranslation(language);

  const locationLink = encodeURIComponent(
    'https://www.google.com/maps/place/Lord+Milner+Hotel+(Matjiesfontein)/@-33.2310257,20.5799933,17z/data=!3m1!4b1!4m9!3m8!1s0x1dd3110f98e906e5:0x40d4cb7334e175dd!5m2!4m1!1i2!8m2!3d-33.2310302!4d20.582182!16s%2Fg%2F1tc_hj29',
  );

  const pageTitle = 'Duminy Troue';

  const isAfrikaans = language === 'afr';
  const weddingTitle = isAfrikaans ? 'TROU!' : 'WEDDING!';

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-[#EFDDCD] pt-5'>
        <LanguageSwitchButtons />

        <div className='text-7xl pt-10 text-[#102135]'>
          <h1>Theunis</h1>
          <h1>&</h1>
          <h1>Mignon</h1>
          {/* <h1 className='pt-10 text-center'>{weddingTitle} 💍</h1> */}
        </div>
        <Header link='theunis-mignon.png' />

        <div className='text-center items-center bg-gradient-to-b from-[#EFDDCD] to-white'>
          {/* subTitle */}
          <div className='pb-14'>
            <p className='text-4xl text-[#102135] pb-2'>
              22-24 {translation.month}, 2024
            </p>
            <a href={locationLink} className='text-3xl'>
              <strong className='text-[#4077a9] py-5 hover:underline'>
                Matjiesfontein
              </strong>
            </a>
          </div>

          {/* Lord Milner picture */}
          <div className='text-center max-w-2xl mx-auto flex align-center justify-center'>
            <img
              src='./images/lord-milner-no-bg.png'
              className='w-[80%] md:w-70 md:px-20'
              alt='Header Image'
            />
          </div>

          {/* Cards for linking to other pages */}
          <Link showBackToHome={false} language={language} />

          {/* Bottom section of the page */}
          <div className='px-2 py-10 mb-3'>
            <p className='leading-6 text-gray-500'>
              {`${translation.waar_die_troue_is_1} `}
              <a href={locationLink}>
                <strong className='text-[#4077a9] hover:underline'>
                  Matjiesfontein
                </strong>
              </a>
              {` ${translation.waar_die_troue_is_2}`}
            </p>
          </div>
        </div>
      </main>
      {/* Footer element */}
      <footer className='border-solid border-t-2 border-[#102135]'>
        <span>Gebou deur Theunis.</span>
      </footer>
    </>
  );
}
