import { getTranslation } from '../lib/language';
import Head from 'next/head';
import LinkCards from '../components/LinkCards';
import Header from '../components/Header';
import useLanguageStore from '../lib/store';
import LanguageSwitchButtons from '../components/LanguageSwitchButtons';

export default function Home() {
  const { language, setLanguage } = useLanguageStore((state) => {
    return {
      language: state.language,
      setLanguage: state.setLanguage,
    };
  });
  const translation: Record<string, any> = getTranslation(language);
  const locationLink =
    'https://www.google.com/maps/place/Lord+Milner+Hotel+(Matjiesfontein)/@-33.2310257,20.5799933,17z/data=!3m1!4b1!4m9!3m8!1s0x1dd3110f98e906e5:0x40d4cb7334e175dd!5m2!4m1!1i2!8m2!3d-33.2310302!4d20.582182!16s%2Fg%2F1tc_hj29';

  return (
    <>
      <Head>
        <title>Duminy Troue</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-[#EFDDCD]'>
        <LanguageSwitchButtons />

        <div className='text-7xl pt-10 text-[#102135]'>
          <h1>Theunis</h1>
          <h1>&</h1>
          <h1>Mignon</h1>
        </div>
        <Header link='theunis-mignon.png' />
        {language === 'afr' ? (
          <>
            <h1 className='text-5xl pb-10'>GAAN TROU!</h1>
          </>
        ) : (
          <>
            <h1 className='text-5xl pb-10'>ARE MARRYING!</h1>
          </>
        )}

        <div className='text-center items-center'>
          {/* subTitle */}
          <p className='text-2xl text-[#102135] pb-10'>
            22-24 {translation.month}, 2024
          </p>

          {/* Cards for linking to other pages */}
          {LinkCards({ showBackToHome: false, language })}

          {/* Bottom section of the page */}
          <div className='border-l-4 border-[#f1cdcd] h-10 mx-auto my-4'></div>
          <div className='px-2 mb-3'>
            <p className='leading-6 text-gray-500'>
              {translation.waar_die_troue_is_1}{' '}
              <a href={locationLink}>
                <strong className='text-[#4077a9] hover:underline'>
                  Matjiesfontein
                </strong>
              </a>{' '}
              {translation.waar_die_troue_is_2}
            </p>
          </div>
        </div>
      </main>
      {/* Footer element */}
      <footer>
        <span>Gebou deur Theunis Duminy.</span>
      </footer>
    </>
  );
}
