import Head from 'next/head';
import Header from '../components/Header';
import useLanguageStore from '../lib/store';
import { getTranslation } from '../lib/language';

export default function Registry() {
  const { language, setLanguage } = useLanguageStore((state) => {
    return {
      language: state.language,
      setLanguage: state.setLanguage,
    };
  });

  const handleLanguageChange = () => {
    const newLanguage = language === 'eng' ? 'afr' : 'eng';
    setLanguage(newLanguage);
  };

  const translation = getTranslation(language);

  return (
    <>
      <Head>
        <title>Registry | Duminy Troue</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <button onClick={handleLanguageChange}>{translation.button}</button>
        <Header link='lord-milner-signed.png' />
        <div>
          <label>
            Ons verwag nie dat enige iemand vir ons geskenke koop nie. Om saam
            ons familie, beste vriende en ander vriende ons groot dag te vier is
            goed genoeg.
          </label>
        </div>
      </main>
      <footer>
        <span>Gebou deur Theunis Duminy.</span>
      </footer>
    </>
  );
}
