import Head from 'next/head';
import Header from '../components/Header';
import useLanguageStore from '../lib/store';
import { getTranslation } from '../lib/language';
import LanguageSwitchButtons from '../components/LanguageSwitchButtons';

export default function Registry() {
  const { language, setLanguage } = useLanguageStore((state) => {
    return {
      language: state.language,
      setLanguage: state.setLanguage,
    };
  });

  const translation = getTranslation(language);

  return (
    <>
      <Head>
        <title>Registry | Duminy Troue</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col align-center justify-center text-center py-5 bg-gradient-to-b from-[#EFDDCD] to-white'>
        <LanguageSwitchButtons />
        <Header link='lord-milner-no-bg-min.png' />
        <div className='px-10 text-justify'>
          <p>
            Ons verwag nie dat enige iemand vir ons geskenke koop nie. Om saam
            ons familie, beste vriende en ander vriende ons groot dag te vier is
            goed genoeg.
          </p>
        </div>
      </main>
      <footer className='border-solid border-t-2 border-[#102135]'>
        <span>Gebou deur Theunis.</span>
      </footer>
    </>
  );
}
