import Head from 'next/head';
import { useState } from 'react';
import RsvpForm from '../components/SubmitRsvp';
import SuccessfulRsvp from '../components/SuccessfulRsvp';
import Header from '../components/Header-1';
import LanguageSwitchButtons from '../components/LanguageSwitchButtons';
import { getTranslation } from '../lib/language';
import useLanguageStore from '../lib/store';

export interface submitMainGuestProps {
  submitMainGuest: (
    isSubmitted: boolean,
    guestData: Record<string, any>,
    isWithSomeone: boolean,
  ) => void;
}

export default function Rsvp() {
  const [mainGuestSubmitted, setMainGuestSubmitted] = useState(false);
  const [guestDetails, setGuestDetails] = useState<Record<string, any>>({});
  const { language, setLanguage } = useLanguageStore((state) => {
    return {
      language: state.language,
      setLanguage: state.setLanguage,
    };
  });

  const translation = getTranslation(language);

  const submitMainGuest = (
    isSubmitted: boolean,
    guestData: Record<string, any>,
  ) => {
    setMainGuestSubmitted(isSubmitted);
    setGuestDetails(guestData);
  };

  return (
    <>
      <Head>
        <title>{`RSVP | Duminy Troue`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <LanguageSwitchButtons />
        <Header link='lord-milner-signed.png' />

        {!mainGuestSubmitted && (
          <div className='text-3xl px-10 py-5 text-center text-[#102135]'>
            <h1>{translation.naweek_bywoon}</h1>
          </div>
        )}

        <div>
          {/* RSVP Form for main guest */}
          {!mainGuestSubmitted && (
            <RsvpForm language={language} onSubmit={submitMainGuest} />
          )}
          {/* Successful RSVP page if no plus one */}
          {mainGuestSubmitted && SuccessfulRsvp(guestDetails, language)}
        </div>
      </main>
      <footer>
        <span>Gebou deur Theunis Duminy.</span>
      </footer>
    </>
  );
}
